name: craft
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  intl: any
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  flutter_svg: ^2.0.10+1
  json_annotation: ^4.8.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  bloc_concurrency: ^0.2.5
  bloc_test: ^9.1.7
  logging: ^1.2.0
  path_provider: ^2.1.3
  injectable: ^2.4.1
  get_it: ^7.6.9
  go_router: ^14.1.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.3

  rust_lib_craft:
    path: rust_builder
  flutter_rust_bridge: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  json_serializable: ^6.7.1
  slang_build_runner: ^3.30.0 # dart run slang - to generate slang files
  injectable_generator: ^2.6.1
  go_router_builder: ^2.5.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true